// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_URVhVGsy0bCNfnVmsAoZcV5h38F1-Rw',
    appId: '1:275451677757:web:8eb95c82e68db01ced6e54',
    messagingSenderId: '275451677757',
    projectId: 'petrolflutterapp',
    authDomain: 'petrolflutterapp.firebaseapp.com',
    storageBucket: 'petrolflutterapp.appspot.com',
    measurementId: 'G-GC97K6GF5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJVYCePF7mGRjEgU0gJ0azD6ZhOBO9t6o',
    appId: '1:275451677757:android:15790dd28126f94ded6e54',
    messagingSenderId: '275451677757',
    projectId: 'petrolflutterapp',
    storageBucket: 'petrolflutterapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKADUqB3SEW4eaZSJEDH9kg8ZFyzSbz88',
    appId: '1:275451677757:ios:b855972f7d4d5e67ed6e54',
    messagingSenderId: '275451677757',
    projectId: 'petrolflutterapp',
    storageBucket: 'petrolflutterapp.appspot.com',
    androidClientId: '275451677757-emjg9u4d7f172cbskkif0tto8qr6b23r.apps.googleusercontent.com',
    iosClientId: '275451677757-6ua5igmeva961h8ij0c20e5392h4b6i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.petrolAppMtaaniTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKADUqB3SEW4eaZSJEDH9kg8ZFyzSbz88',
    appId: '1:275451677757:ios:b855972f7d4d5e67ed6e54',
    messagingSenderId: '275451677757',
    projectId: 'petrolflutterapp',
    storageBucket: 'petrolflutterapp.appspot.com',
    androidClientId: '275451677757-emjg9u4d7f172cbskkif0tto8qr6b23r.apps.googleusercontent.com',
    iosClientId: '275451677757-6ua5igmeva961h8ij0c20e5392h4b6i1.apps.googleusercontent.com',
    iosBundleId: 'com.example.petrolAppMtaaniTech',
  );
}
